### PR TITLE
Follow awesome guidelines

### PR DESCRIPTION
**Pull request by NTBBloodbath**
This PR has the purpose of following the [awesome guidelines] in order to open a PR in [sindresorhus/awesome] and thus add this repository to the main list.

Requirements:

- [x] Should have a [license], CC0 is recommended.
- [x] Should have contributing guidelines ([7c7001d](https://github.com/rockerBOO/awesome-neovim/pull/98/commits/fc7001dc7f0a0fb36794497fdbefcf8da18a8661)).
- [ ] Should pass awesome linter
- [x] Should have `awesome` and `awesome-list` topics

On-the-go changelog:

- Added contributing guidelines
- Added a workflow to run `awesome-lint` on each push
- Fixed `awesome-lint` issues

[license]: https://github.com/sindresorhus/awesome/blob/main/awesome.md#choose-an-appropriate-license
[awesome guidelines]: https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-awesome-list
[sindresorhus/awesome]: https://github.com/sindresorhus/awesome

### CODE REVIEW

**Comment by NTBBloodbath** [comment]
Everything is ready on my side, you need to add the license and the repository topics to pass the linter.

> **IMPORTANT:** Until all the checkboxes are complete, no merge should be done.

**Comment by tversteeg** [comment]
I can merge the PR, but I can't change the tags. You can also add the license to the PR.

**Comment by tversteeg** [comment]
That's up to @rockerBOO, but I can't think of any reasons not to add a CC license?

**Comment by NTBBloodbath** [comment]
Neither do I, however I'm not the owner of the repository so I felt that I cannot decide which license to use.

I think it's okay to merge now, then when @rockerBOO sees the mentions I suppose he will add the necessary topics.

After the topics are in, the awesome linter should go through without any problem.

**Comment by rockerBOO** [comment]
Thank you @NTBBloodbath ! Should be good to go now. We can work out the awesome-linter workflow as we go.

**Pull request merged**
