### PR TITLE
Adding my vim colorscheme. 

### PR DESCRIPTION
**Pull request by Mangeshrex**
Notes: 
* Make sure you add a `.` to the end of your lines. This is to conform to `awesome-list` linting and requirements.
* Make sure it's not already on the list.

### CODE REVIEW

**Comment by tversteeg** [comment]
Does this colorscheme support treesitter notations?
Thanks for the PR!

Does the colorscheme support treesitter syntax? We only add colorschemes with those to the repo.

**Comment by Mangeshrex** [comment]
Hey, can you please check wether it does or not? Sorry cause I never tried it with nvim-treesitter so not sure whether it does or not

**Comment by tversteeg** [comment]
It doesn't at the moment, you can add these by implementing the treesitter highlight groups. See `:h nvim-treesitter-highlights`.

**Comment by Mangeshrex** [comment]
Hmm I'll check and update these things today thank you 👍

**Comment by tversteeg** [comment]
No problem, if you add these you can reopen this PR.

**Comment by Mangeshrex** [comment]
Ok sure

**Comment by Mangeshrex** [comment]
Hey how do i reopen this pr ? i dont see any option here

**Pull request closed without merging**
