### PR TITLE
Feat/add pr title checker github action

### PR DESCRIPTION
**Pull request by mosheavni**
Verify the title conforms with the requirement

> The title of the pull request is ```Add/Update/Remove `username/repo` ``` (notice the backticks around ``` `username/repo` ```) when adding a new plugin.

### CODE REVIEW

**Review by kang8 — CHANGES_REQUESTED** [review]
Can add the corresponding reminders in [CONTRIBUTING.md](https://github.com/rockerBOO/awesome-neovim/blob/main/CONTRIBUTING.md#submitting-pull-requests).

**Comment by mosheavni** [comment]
> Can add the corresponding reminders in [CONTRIBUTING.md](https://github.com/rockerBOO/awesome-neovim/blob/main/CONTRIBUTING.md#submitting-pull-requests).

not sure what you mean.

**Comment by tversteeg** [comment]
Thanks for the PR!

**Comment by kang8** [comment]
> not sure what you mean.

Sorry for not making it clear.

You can add instructions for limiting PR in CONTRIBUTING.md, such as *Ensuring that your PR title follows [this regexp rule](https://github.com/rockerBOO/awesome-neovim/blob/7ac08e49deee2d01c4b017e038882acb6a0a768e/.github/workflows/pr-title.yml#L14)*.

@tversteeg What do you think? If you think it's good, I'm happy to submit a PR.

**Comment by tversteeg** [comment]
> @tversteeg What do you think? If you think it's good, I'm happy to submit a PR.

Yes that's a great idea! You can use the PR checklist as a starting point.

**Pull request merged**
