### PR TITLE
new plugins

### PR DESCRIPTION
**Pull request by siduck76**

### CODE REVIEW

**Comment by tversteeg** [comment]
Thanks for the PR!

You are missing a `.` at the end of some lines, when you add that I can merge your PR.

See the failing CI.

**Comment by siduck76** [comment]
oh sorry! I added the missing ones but the CI still fails :(

**Comment by tversteeg** [comment]
There's two more missing:
```
  ✖  315:66  List item description must start with valid casing  remark-lint:awesome-list-item
  ✖  512:60  List item description must start with valid casing  remark-lint:awesome-list-item
```

**Comment by gegoune** [comment]
https://github.com/noib3/cokeline.nvim has literary no documentation at all. Barely 'awesome' at all at the moment.

**Comment by siduck76** [comment]
fixed!

**Comment by tversteeg** [comment]
I've removed cokeline, a new PR can be made once it's a bit more up to standards.

Thanks for the PR!

**Pull request merged**
