### PR TITLE
Add Discord Rich Presence, Firenvim and Doom Nvim

### PR DESCRIPTION
**Pull request by Vhyrro**
Title pretty much says it all, added a nice discord rich presence plugin, firenvim for browser integration and an awesome project I found yesterday called doom-nvim which should be perfect for newcomers to neovim.

### CODE REVIEW

**Comment by Vhyrro** [comment]
Also added AckslD/nvim-revJ.lua now :)

**Comment by ttys3** [comment]
@Vhyrro  I found there are two doom nvim:

`https://github.com/NTBBloodbath/doom-nvim`

`https://github.com/yttrion/doomnvim`

**Comment by Vhyrro** [comment]
That is true, however it seems that the other doom for neovim hasn't been updated in a while, also it's written in vimscript whilst the one I found is written in lua. It also seems to be more promising in general in my opinion

**Comment by Vhyrro** [comment]
Spent a few hours scouring the internet for some more plugins and chose the most interesting and useful ones I could find! All of them written in lua of course :)

**Comment by ttys3** [comment]
> That is true, however it seems that the other doom for neovim hasn't been updated in a while, also it's written in vimscript whilst the one I found is written in lua. It also seems to be more promising in general in my opinion

+1 for the lua one

**Comment by rockerBOO** [comment]
Thank you @Vhyrro ! This looks great!

**Pull request merged**
