### PR TITLE
add calltree

### PR DESCRIPTION
**Pull request by ldelossa**
Signed-off-by: ldelossa <louis.delos@gmail.com>

Checklist:

- [x] The plugin is specifically built for Neovim.
- [x] The lines end with a `.`. This is to conform to `awesome-list` linting and requirements.
- [x] It's not already on the list.

### CODE REVIEW

**Comment by tversteeg** [comment]
Thanks for the PR!

Sorry for the late response and weird commits, GitHub messed the merging of main in your branch up. If you can fix those (you can just add a new commit, I'll squash it) I can merge it.

**Comment by ldelossa** [comment]
hey @tversteeg  

wasn't quite sure how to fix that - I just rebased this branch against latest master so it should merge cleanly.

**Comment by tversteeg** [comment]
That's also fine, thanks again!

**Comment by ldelossa** [comment]
Thank you :)

**Pull request merged**
