### PR TITLE
Add coc.nvim and vim-floaterm

### PR DESCRIPTION
**Pull request by nynagnz**

### CODE REVIEW

**Comment by tversteeg** [comment]
Thanks for the PR!

You are missing a `.` at the end of the line, when you add that I can merge your PR. See the failing CI.

**Comment by nynagnz** [comment]
Done.

**Comment by rockerBOO** [comment]
Thank you @nynagnz !

**Comment by pianocomposer321** [comment]
Neither of these are neovim specific…isn’t this repo supposed to be for neovim specific plugins?

**Pull request merged**
