### PR TITLE
Add `AckslD/nvim-gfold.lua`

### PR DESCRIPTION
**Pull request by AckslD**
Checklist:

- [x] The plugin is specifically built for Neovim.
- [x] The lines end with a `.`. This is to conform to `awesome-list` linting and requirements.
- [x] It's not already on the list.
- [x] If it's a colorscheme, it supports treesitter syntax.
- [x] The title of the pull request is ```Add `username/repo` ``` when adding a new plugin.

### CODE REVIEW

**Comment by tversteeg** [comment]
Thanks for the PR!

Something went wrong with the syntax of your line, when you fix that I can merge your PR. See the failing CI.

**Comment by AckslD** [comment]
@tversteeg I think the issue was already there before? It complains about https://github.com/[tjdevries/colorbuddy.nvim](https://github.com/tjdevries/colorbuddy.nvim) being there twice.

**Comment by tversteeg** [comment]
You're right, my bad, I fixed it.

**Comment by AckslD** [comment]
Thanks @tversteeg

**Pull request merged**
