### PR TITLE
Reformat modules of `echasnovski/mini.nvim`

### PR DESCRIPTION
**Pull request by echasnovski**
Checklist:

- [x] The plugin is specifically built for Neovim.
- [x] The lines end with a `.`. This is to conform to `awesome-list` linting and requirements.
- [x] It's not already on the list.
- [ ] The title of the pull request is ```Add `username/repo` ``` when adding a new plugin.

### CODE REVIEW

**Comment by tversteeg** [comment]
Thanks for the PR.

The format is incorrect, the URL should be `username/repo`, I didn't notice that was also wrong in the line above, could you fix both?

**Comment by echasnovski** [comment]
The fist URL is to the module of plugin, so not really suitable for `username/repo` template. It is applied in `echasnovski/mini.nvim` later in URL. I guess something like `echasnovski/mini.nvim#mini.jump2d` is possible, but that also violates `username/repo` template (and looks worth in my opinion).

**Comment by tversteeg** [comment]
Sorry I don't mean the actual URL but how it's displayed:

```markdown
[echasnovski/mini.jump2d](https://github.com/echasnovski/mini.nvim#minijump2d)
```

**Comment by echasnovski** [comment]
I understood that. My main concern here is that it still doesn't fit the `username/repo` template and is a bit misleading (as it doesn't imply `https://github.com/echasnovski/mini.jump2d` URL and can't be used directly as `echasnovski/mini.jump2d` in `packer`).

I don't think that is the best solution, but if that is the only way to add modules from 'mini.nvim' (all of them doesn't follow `username/repo` and were accepted earlier), I'll sure change current entry. If needed, change all other 'mini.nvim' entries (either here or in separate PR, whatever you think is best).

**Comment by tversteeg** [comment]
Ah sorry that's quite inconsistent of me.

I previously didn't really consider the "single git repo" part. I do think just the name ruins the format somewhat. I think it's best to use the same format as `nvim-cmp`. So something like this:

```markdown
- [echasnovski/mini.jump2d](https://github.com/echasnovski/mini.jump2d) - ...
  - [..#mini.jump](https://github.com/echasnovski/mini.jump2d#minjmp) - ...
```

This way it's more obvious that it's part of the same repository and it's also grouped together with indentation.

**Comment by echasnovski** [comment]
Hmm... I think we are still not on the same page here.

There is a single git repo [echasnovski/mini.nvim](https://github.com/echasnovski/mini.nvim), which is a collection of independent Lua modules for completely different tasks: surrounding text ([`mini.surround`](https://github.com/echasnovski/mini.nvim#minisurround)), working with indent scope ([`mini.indentscope`](https://github.com/echasnovski/mini.nvim#miniindentscope)), and others with *total of 18 modules and 1 colorscheme*. Each module is a new creation which can be used opt-in as generic plugin in common sense. The main difference is that they all are "packaged" in one git repo. All of these modules are currently listed here, which provided great promotion to them and for which I am truly grateful.

This PR was initially intended to add another, new [mini.jump2d](https://github.com/echasnovski/mini.nvim#minijump2d) module (number 18). It is different from the currently present 'mini.jump' module.

So taking into account your concerns about "single git repo" and "just the name ruins the format", I see several ways to handle this:
1. Move all 18 current entries to a sub-list of a new `echasnovski/mini.nvim` entry. I would really, really don't like this option as it greatly limits their exposure: users looking for commenting plugins won't look outside of 'Comment" section. And there is a problem of picking the right section, as this is not a "Preconfigured Configuration", because all modules are originally created.
1. Update all current entries to the following format:
``[`echasnovski/mini.nvim#mini.surround`](https://github.com/echasnovski/mini.nvim#minisurround) - module of `echasnovski/mini.nvim` for ...`` (or use just ``module of `mini.nvim` for ... `` to not spam with username).
1. Leave everything as it is now. Always an option :)

My preferred way would be to leave everything as it is now, but if you have strong opinion about "just the name ruins the format", option 2 seems like a good compromise.

**Comment by tversteeg** [comment]
Thanks for elaborating on it.

With that in mind, I think option 2 is the preferred one. That way it's still obvious to which repository it belongs but also denotes it as a separate plugin.

```module of `mini.nvim` for ..``` would also be preferable since the username is already in the title.

**Comment by echasnovski** [comment]
Sounds good. I'll update this PR tomorrow.

**Comment by echasnovski** [comment]
Updated formatting. Hope it is good to go now.

**Comment by tversteeg** [comment]
Thanks for all the effort!

**Pull request merged**
