### PR TITLE
Add `lervag/vimtex`

### PR DESCRIPTION
**Pull request by tapyu**
Checklist:

- [x] The plugin is specifically built for Neovim.
- [x] The lines end with a `.`. This is to conform to `awesome-list` linting and requirements.
- [x] It's not already on the list.
- [x] If it's a colorscheme, it supports treesitter syntax.
- [x] The title of the pull request is ```Add `username/repo` ``` when adding a new plugin.

As far as I understood, my PR statement [`#381`](https://github.com/rockerBOO/awesome-neovim/pull/381) was wrong about `lervag/vimtex` not being a plugin specifically for Neovim. I told so just because it works on `vim` as well, but I've notice that there are other plugins in this list in the same situation.

I humbly ask to consider the insertion of this plugin to the list.

### CODE REVIEW

**Comment by pianocomposer321** [comment]
> Err. VimTeX is not a neovim-specific plugin. It's written in vimscript and works perfectly fine with regular vim

Obviously not my PR, but I think the point is that there are already plugins in the list that are not neovim specific. Is the plan to remove these plugins at some point in the future?

**Comment by tapyu** [comment]
> It's written in vimscript

So "not being neovim-specific" = "written in vimscript"? I understand. Thanks for clarify, so disregard this PR :)

**Comment by krishnakumarg1984** [comment]
> Obviously not my PR, but I think the point is that there are already plugins in the list that are not neovim specific.

Are there? Could you please point this out here so that the maintainers can take an appropriate decision on those.

**Comment by tapyu** [comment]
> "not being neovim-specific" = "written in vimscript"

IMHO, I must the stated somewhere. I didn't know that it was the point.

> Are there?

Depends, what is being specific for neovim? If it is no being written in vimscript. I think that there aren't.

**Comment by krishnakumarg1984** [comment]
I think no plugin in this list works in regular vim.

**Comment by pianocomposer321** [comment]
If you're including color schemes, this isn't true. The list includes everforest, edge, sonokai, and gruvbox material, all of which work on regular vim.

**Comment by thetic** [comment]
https://github.com/lervag/vimtex/blob/9ffbe63a2055b59b09b18b1cd682e0b2703cc898/doc/vimtex.txt#L4072=

**Comment by tapyu** [comment]
From the @thetic 's comment. I think that the question for @krishnakumarg1984 is: yes.

**Comment by yhu266** [comment]
Isn't this autocomplete feature provided by `hrsh7th/cmp-omni`?
I think it's fine to add `hrsh7th/cmp-omni` to this list, but I don't think VimTex is a good fit here.

**Comment by tversteeg** [comment]
I agree with the above sentiment, it's fine to add the plugin to the list of `nvim-cmp` sources, but as a standalone plugin it doesn't meet the criteria for being, at least partially, specifically written for Neovim.

**Pull request closed without merging**
