### PR TITLE
Molleweid

### PR DESCRIPTION
**Pull request by molleweide**

### CODE REVIEW

**Comment by molleweide** [comment]
added one more proj >> reaper-keys

**Comment by tversteeg** [comment]
Thanks for the PR! Can you also add descriptions to the other 2 URL's?

**Comment by molleweide** [comment]
you are right!! i fix!

**Comment by molleweide** [comment]
i squashed my commits to make it more condensed. I hade just learnt about rebasing and patching
myself. Now it doesn't pass checks. Should I not have done this?

**Comment by tversteeg** [comment]
No squashing it is not the problem. The problem is that you didn't remove the Music section yet. So the links are double, which is what the CI is complaining about.

**Comment by molleweide** [comment]
Something is wierd because I did remove it like you said and I can see that it is removed
if on my gith fork. But it did not update here!? Hmm.

**Comment by tversteeg** [comment]
Did you do that from the proper `molleweid` branch?

**Comment by molleweide** [comment]
yes

**Comment by molleweide** [comment]
Hey! I have double checked a couple of times now to make sure. But of course
there is something that I did that caused this - I just don't understand what.
Anyways, I hope I haven't wasted too much of your time.

**Comment by rockerBOO** [comment]
You made 2 pull requests. The previous PR was merged into master, adding the music category, and 2 plugins. In this PR you are adding an additional plugin, but have the other 2 plugins in this PR. 

I think the easiest is to make a new branch off the current main branch, and add the single plugin that you have in this PR. If you want to remove the Music category now, you'll need to remove it from the main branch. 

Alternatively you could merge in the current main branch from this repo into your branch. Then fix up the duplicates in 2 categories.

**Pull request closed without merging**
