### PR TITLE
Remove nvim-reload

### PR DESCRIPTION
**Pull request by McAuleyPenney**
nvim-reload is now archived

### CODE REVIEW

**Comment by tversteeg** [comment]
I'd rather remove it from the list if it's archived to be honest…

**Comment by McAuleyPenney** [comment]
For sure! I'm not the author of the plugin. I was just checking it out and noticed, so I figured I'd make a note of it for others. I can go ahead and remove it if you'd like.

**Comment by McAuleyPenney** [comment]
updated!

**Comment by tversteeg** [comment]
Thanks!

**Pull request merged**
