### PR TITLE
`Plugin` subcategories re-organization (#557)

### LINKED ISSUE #557: `Plugin` subcategories re-organization
Would make quickly finding categories easier imo, especially when taking a look from something like the mobile app (no search-bar).
If you agree with this I can make a PR no problem.

### PR DESCRIPTION
**Pull request by T-727**
(currently WIP)
Closes #557
"sub-subcategories", re-ordering, and general re-organization.
Changes are marked per commit below.

`40a1698`:

- `Fuzzy Finder`, `File Explorer`, & `Project` follow each other
- `Motion`, `Keybinding`, `Mouse`, & `Scrolling` follow each other

- `Colorscheme creation` became a sub of `Colorscheme`
- `Quickfix` became a sub of `Debugging`
- `Competitive Programming` became a sub of `Game`
- `Github` became a sub of `Git`
- `Scrollbar` became a sub of `Scrolling`
- `Comment` became a sub of `Editing support`
- `Indent` became a sub of `Formatting`
- `Tmux` became a sub of `Split and Window`

### CODE REVIEW

**Comment by T-727** [comment]
`5ca53d2`:
- `UI` now links to the official wiki page
- `Programming languages support` follows `Lsp` and `Completion`
- `Web development` became a sub of `Programming languages support`
- `Statusline`, ... til `Startup` moved below `Colorscheme`
- `Test` follows `Debugging`
- Removed `Browser integration` as it falls under `UI`

**Comment by T-727** [comment]
`be608e9`:

- `Language` moved below `Markdown / LaTeX`
- `Search` moved above `Fuzzy Finder`
- Removed `Collaborative Editing` and moved [jbyuki/instant.nvim](https://github.com/jbyuki/instant.nvim) to `Utility`
- `Code Runner` moved below `Test`
- [onsails/diaglist.nvim](https://github.com/onsails/diaglist.nvim), [folke/trouble.nvim](https://github.com/folke/trouble.nvim), [folke/lsp-colors.nvim](https://github.com/folke/lsp-colors.nvim), and [git.sr.ht/~whynothugo/lsp_lines.nvim](https://git.sr.ht/~whynothugo/lsp_lines.nvim) moved to `Diagnostics`
- Go plugins in `Programming languages support` follow each other
- [crusj/structrue-go.nvim](https://github.com/crusj/structrue-go.nvim), [someone-stole-my-name/yaml-companion.nvim](https://github.com/someone-stole-my-name/yaml-companion.nvim) and [cuducos/yaml.nvim](https://github.com/cuducos/yaml.nvim) moved to `Programming languages support`
- [nyngwang/NeoNoName.lua](https://github.com/nyngwang/NeoNoName.lua), [famiu/bufdelete.nvim](https://github.com/famiu/bufdelete.nvim) and [echasnovski/mini.nvim#mini.bufremove](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-bufremove.md) moved to `Split and Window`
- [max397574/better-escape.nvim](https://github.com/max397574/better-escape.nvim) moved to `Keybinding`
- [m00qek/plugin-template.nvim](https://github.com/m00qek/plugin-template.nvim) and [ellisonleao/nvim-plugin-template](https://github.com/ellisonleao/nvim-plugin-template) moved to `Boilerplate`
- [linty-org/readline.nvim](https://github.com/linty-org/readline.nvim) moved to `Motion`

**Comment by tversteeg** [comment]
Thank you so much, I'm very happy with this so far! Do you still want to add more changes or shall I merge it?

**Comment by T-727** [comment]
`5d74f62`:

- `Terminal Integration` moved below `Utility`
- `Media` and `Note Taking` moved above `Utility`
- `Game` and `Preconfigured Configuration` moved to the bottom

**Comment by T-727** [comment]
There @tversteeg. 🙂

**Pull request merged**
