### PR TITLE
Add the top links

### PR DESCRIPTION
**Pull request by tanloong**
Add a link after each item for jumping back to the "Contents" section.

### CODE REVIEW

**Comment by tversteeg** [comment]
Thanks for the PR, I like this change, but unfortunately the awesome-lint doesn't…

**Comment by loicreynier** [comment]
I believe that the `awesome-lint` warnings could be disabled by adding `<!--lint ignore double-link-->` before each heading.

**Comment by tanloong** [comment]
Sorry, I failed. 

No need for running  `awesome-lint`. Even if my last commit works for "wishlist", it still won't pass, according to [this comment](https://github.com/sindresorhus/awesome-lint/issues/121#issuecomment-691241261).

**Comment by tversteeg** [comment]
That's too bad, thanks for all the effort though!

**Pull request closed without merging**
