### PR TITLE
Add `chrisgrieser/alfred-neovim-utilities`

### PR DESCRIPTION
**Pull request by chrisgrieser**
I created a new h3 heading, since it's an external tool that neither fits into "version manager" nor "boilerplate" – hope that's alright?

### Repo URL:

https://github.com/chrisgrieser/alfred-neovim-utilities

### Checklist:

- [x] The plugin is specifically built for Neovim, or if it's a colorscheme, it supports treesitter syntax.
- [x] The lines end with a `.`. This is to conform to `awesome-list` linting and requirements.
- [x] The title of the pull request is ```Add/Update/Remove `username/repo` ``` (notice the backticks around ``` `username/repo` ```) when adding a new plugin.
- [x] The description doesn't mention that it's a Neovim plugin, it's obvious from the rest of the document. No mentions of the word `plugin` unless it's related to something else.
- [x] The description doesn't contain emojis.
- [x] Neovim is spelled as `Neovim` (not `nvim`, `NeoVim` or `neovim`), Vim is spelled as `Vim` (capitalized), Lua is spelled as `Lua` (capitalized), Tree-sitter is spelled as `Tree-sitter`.
- [x] Acronyms should be fully capitalized, for example `LSP`, `TS`, `YAML`, etc.

### CODE REVIEW

**Comment by tversteeg** [comment]
I think new headings should at least contain multiple items.

**Comment by chrisgrieser** [comment]
well, where should I put it then? there isn't really any existing category that fits 🤔

**Comment by tversteeg** [comment]
How about "Utility"?

**Comment by chrisgrieser** [comment]
It isn't a nvim plugin though, but rather a plugin for Alfred (macOS launcher app), which provides features related to nvim. 

So putting it under "Utility" would be wrong, since "Utility" is a subcategory of the nvim-plugin section.

**Comment by tversteeg** [comment]
Ah now I understand, in that case I don't see an alternative.

**Comment by chrisgrieser** [comment]
good idea, I have renamed it

**Pull request merged**
