### PR TITLE
Remove `iamcco/markdown-preview.nvim`

### PR DESCRIPTION
**Pull request by tversteeg**
Reverts rockerBOO/awesome-neovim#571

### CODE REVIEW

**Comment by ofirgall** [comment]
Why this rule exist, doesn't this list should contain the best plugins for nvim?
Currently it's the only plugin that provides an actual markdown preview with easy setup, awesome lists are used as the source of plugins for many users, removing this plugin from the list just makes the user choose a less polished plugin.

**Comment by tversteeg** [comment]
This rule exists because there are already plenty of [lists in which you can find both](https://github.com/rockerBOO/awesome-neovim#vim), so a list for plugins just for Neovim makes sense. It also makes more sense technically because Neovim-only plugins tend to be written in Lua.

**Comment by smjonas** [comment]
I don't really get the reasoning behind removing `markdown-preview` either. Following that logic, you should remove `copilot.vim` but not `copilot-cmp`. This just makes it harder for Neovim users to find good plugins.

**Comment by tversteeg** [comment]
I think discussing this in this PR is not the right place. Please open an issue for it, so more people can chime in.

**Pull request merged**
